#spring:
#  security:
#    user:
#      name: test_user
#      password: test_password

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.31.75:3307/spring-security-demo-db?useSSL=false&characterEncoding=utf-8&useUnicode=true&characterEncodeing=UTF-8&allowPublicKeyRetrieval=true&serverTimezone=Asia/Shanghai
    username: root
    password: Justgo123[].
  thymeleaf:
    prefix: classpath:/templates/
  mvc:
    static-path-pattern: /static/**
  web:
    resources:
      static-locations: classpath:/static
  redis:
    # Redis 数据库索引（默认为 0）
    database: 0
    # Redis 服务器地址
    host: 192.168.31.75
    # Redis 服务器连接端口
    port: 6380
    # Redis 服务器连接密码（默认为空）
    password: Ik4X7EwVmmxihvDmwMtyKVge80pl2t8p
    # 连接超时时间（毫秒）
    timeout: 5000